variables:
  KUBE_CONTEXT: devops_world1/kubernetes-connection:k8s-connection
  DOCKERIZE_IMAGE_TAG: ci-${CI_JOB_ID}-${CI_COMMIT_SHORT_SHA}
stages:
    - build
    - deploy

build_image:
  image: docker
  stage: build
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/devops_world1/kubernetes-ci-cd-pipeline/nginxcicd:v2 .
    - docker push $CI_REGISTRY/devops_world1/kubernetes-ci-cd-pipeline/nginxcicd:v2
    - echo "Image successfully built"

deploy_project:
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  stage: deploy
  script:
    - kubectl config use-context $KUBE_CONTEXT
    - echo "Deployment of Login-app to kubernetes"
    - kubectl apply -f $CI_PROJECT_DIR/k8s-src/.
    - kubectl get pods -o wide