apiVersion: v1
kind: Service
metadata:
  labels:
    app: login-svc
  name: login-svc
spec:
  ports:
  - name: login-svc
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31000
  type: NodePort
  selector:
    run: webapp
