apiVersion: v1
kind: Pod
metadata:
  labels:
    run: webapp
  name: webapp
spec:
  containers:
    - image: registry.gitlab.com/devops_world1/cicd-kubernetes/nginxcicd:v2
      name: webapp
  restartPolicy: Always
  imagePullSecrets:
     - name: docker-registry-login-creds 
